sudo: false
language: groovy
script:
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r test-requirements.txt

    # mobile app
    - pip install -r mobile_app/resources/requirements.txt
    - pep8 mobile_app/resources
    - nosetests mobile_app/resources -v --with-coverage --cover-package=mobile_app

    - export CI_SYSTEM='travis'
    - ./gradlew check --stacktrace --info
