#!/bin/bash
set -e

IFS=',' read -ra SCRIPTSTORUN <<<"$SCRIPTS"

PACKAGESTOINSTALL=$(echo $PACKAGES | tr , " ")

IFS=',' read -ra REPOS <<<"$REPO_NAMES"

failed_repos=()

all_repos="$WORKSPACE/edx-repos"
mkdir -p "$all_repos"

all_venvs="$WORKSPACE/edx-venvs"
mkdir -p "$all_venvs"

for repo in "${REPOS[@]}"; do
  repo_dir="$all_repos/$repo"

  rm -rf "$repo_dir"
  if git clone "https://github.com/$ORG/$repo.git" "$repo_dir"; then true; else failed_repos+=("${repo}") && continue; fi

  venv_dir="$all_venvs/$repo"
  virtualenv --python=python"$PYTHON_VERSION" "$venv_dir" --clear -q
  source "$venv_dir/bin/activate"

  echo "Upgrading pip..."
  if pip install pip==20.0.2; then true; else failed_repos+=("${repo}") && continue; fi

  echo "Running cleanup..."
  cd "$repo_dir"

  if pip install $PACKAGESTOINSTALL; then true; else failed_repos+=("${repo}") && continue; fi

  for element in "${SCRIPTSTORUN[@]}"; do
    # shellcheck disable=SC2091
    if $(echo "$element"); then true; else failed_repos+=("${repo}") && continue; fi
  done

  echo "Running script to create PR..."
  cd "$WORKSPACE/testeng-ci"
  if pip install -r requirements/base.txt; then true; else failed_repos+=("${repo}") && continue ; fi
  message="$(cat <<EOF
Python code cleanup by the cleanup-python-code Jenkins job.

This pull request was generated by the cleanup-python-code Jenkins job, which ran
\`\`\`
$SCRIPTS
\`\`\`

The following packages were installed:
\`$PACKAGES\`
EOF
)"
  if python -m jenkins.pull_request_creator --repo-root="$repo_dir" \
            --base-branch-name="cleanup-python-code" --commit-message="$message" \
            --pr-title="Python Code Cleanup" --pr-body="$message" \
            --user-reviewers="$PR_USER_REVIEWERS" --team-reviewers="$PR_TEAM_REVIEWERS" \
            --no-delete-old-pull-requests
  then
    true
  else
    deactivate
    cd "$WORKSPACE"
    rm -rf "$venv_dir"
    failed_repos+=("${repo}") && continue
  fi

  deactivate
  cd "$WORKSPACE"
  rm -rf "$venv_dir"

done

if [ ${#failed_repos[@]} -ne 0 ]; then
  echo "Following repositories failed during execution of cleanup scripts causing the job to fail"
  echo "${failed_repos[@]}"
  exit 1
fi
