# Configuration for exporting data for all orgs from Jenkins.
# This config makes some assumptions that are only valid for
# Jenkins-managed shiningpanda virtual environments.
#
# As part of the job, a symlink is created to the django-admin.py
# executable in the virtual environment workspace, which is subject to
# change. To fix this, we use the variable ${WORKSPACE} that is
# overridden in the Jenkins shell task with the appropiate value.

defaults:
  auth_file: '{WORKSPACE}/analytics-secure/analytics-exporter/task-auth.json'
  gpg_master_key: analytics@edx.org
  gpg_keys: gpg-keys
  work_dir: /var/lib/jenkins/tmp/analytics-exporter
  external_prefix: ''
  output_bucket: course-data
  pipeline_bucket: edx-analytics-export
  output_prefix: ''
  se_bucket: edx-analytics-stackexchange
  django_admin: ''
  django_pythonpath: ''
  django_settings: lms.envs.analytics_exporter
  django_cms_settings: cms.envs.analytics_exporter
  django_database: read_replica
  mongo_collection: contents
  sql_user: analytics001
  sql_db: wwc
  monitor: true
  graphite_host: graphite.analytics.edx.org
  graphite_port: 2003
  graphite_prefix: edx.analytics.research
  # Config to limit how many years of data the analytics exporter job dumps.
  # This is the number of years in the past from today's date
  time_constraint: 3

environments:
  prod:
    lms_config: ${WORKSPACE}/remote-config/prod-edx/lms.yml
    studio_config: ${WORKSPACE}/remote-config/prod-edx/studio.yml
    mongo_host: prod-edx-mongo-1.edx.org:27017,prod-edx-mongo-2.edx.org:27017,prod-edx-mongo-3.edx.org:27017,prod-edx-mongo-4.edx.org:27017
    mongo_db: comments-prod
    name: prod-analytics
    sql_host: prod-edx-edxapp-readonly.rds.edx.org
  edge:
    lms_config: ${WORKSPACE}/remote-config/prod-edge/lms.yml
    studio_config: ${WORKSPACE}/remote-config/prod-edge/studio.yml
    mongo_host: prod-edge-mongo-1.edx.org:27017,prod-edge-mongo-2.edx.org:27017,prod-edge-mongo-3.edx.org:27017,prod-edge-mongo-4.edx.org:27017
    mongo_db: comments-edge
    name: prod-edge-analytics
    sql_host: prod-edge-edxapp-readonly.rds.edx.org
